spring.application.name=lumiflow

# 1. Atualize a URL para o driver do PostgreSQL
spring.datasource.url=${DB_POSTGRES_URL:jdbc:postgresql://localhost:5432/lumiflow}
spring.datasource.username=${DB_POSTGRES_USERNAME:postgres}
spring.datasource.password=${DB_POSTGRES_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configure a plataforma e o dialeto do Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# 3. Flyway ativo
spring.flyway.enabled=true

spring.thymeleaf.cache=false

# Logging padrão - apenas INFO
logging.level.root=INFO
logging.level.br.com.lumiflow=INFO