spring.application.name=lumiflow

spring.datasource.url=${DB_MYSQL_URL}
spring.datasource.username=${DB_MYSQL_USERNAME}
spring.datasource.password=${DB_MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.thymeleaf.cache=false

logging.level.org.springframework.web=DEBUG

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE